package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"runtime"
)

const wireBuildPrefix = "com.yasyf.cc-interact.interaction/"

func main() {
	check := flag.Bool("check", false, "verify the generated wire build")
	flag.Parse()
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		fatalf("locate generator source")
	}
	dir := filepath.Dir(filepath.Dir(source))
	schemaPath := filepath.Join(dir, "interaction.schema.json")
	outputPath := filepath.Join(dir, "wirebuild_gen.go")
	raw, err := os.ReadFile(schemaPath)
	if err != nil {
		fatalf("read schema: %v", err)
	}
	canonical, err := canonicalJSON(raw)
	if err != nil {
		fatalf("canonicalize schema: %v", err)
	}
	sum := sha256.Sum256(canonical)
	wireBuild := wireBuildPrefix + hex.EncodeToString(sum[:]) + "/v1"
	generated, err := format.Source([]byte(fmt.Sprintf(`// Code generated by go generate ./daemon; DO NOT EDIT.

package daemon

// WireBuild is the exact shared cc-interact interaction-schema identity.
const WireBuild = %q
`, wireBuild)))
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if *check {
		current, err := os.ReadFile(outputPath)
		if err != nil {
			fatalf("read generated source: %v", err)
		}
		if !bytes.Equal(current, generated) {
			fatalf("%s is stale; run go generate ./daemon", outputPath)
		}
		return
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func canonicalJSON(raw []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var schema any
	if err := decoder.Decode(&schema); err != nil {
		return nil, err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err == nil {
		return nil, fmt.Errorf("trailing JSON value")
	} else if err != io.EOF {
		return nil, err
	}
	return json.Marshal(schema)
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "protocolgen: "+format+"\n", args...)
	os.Exit(1)
}
