// Code generated by go generate ./daemon; DO NOT EDIT.

package daemon

// WireBuild is the exact shared cc-interact interaction-schema identity.
const WireBuild = "com.yasyf.cc-interact.interaction/022f2ae95776fa2171ec24b2168ded0fd0833b525154026707575f28a50dfb14/v1"
