// Code generated by go generate ./daemon; DO NOT EDIT.

package daemon

// WireBuild is the exact shared cc-interact interaction-schema identity.
const WireBuild = "com.yasyf.cc-interact.interaction/2f18d8a1998d253f57d67e6ec6c549b32aa230676f9dd9b439a2ae63b3ea07d8/v1"
